version: "3.8"
name: web_hw13
services:
  pg:
    image: postgres
    expose:
      - "5432"
    # ports:
    #   - "5432:5432"
    env_file:
      - ./.env

  code :
    build: ./
    image: lexxai/web_hw13:latest
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    depends_on:
      - pg

